# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1103, 748)
        MainWindow.setStyleSheet("background-color: #07090B")
        MainWindow.setAnimated(True)
        
        # Central widget that will contain all other widgets
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        
        # Main layout for the central widget
        self.main_layout = QtWidgets.QHBoxLayout(self.central_widget)
        self.main_layout.setContentsMargins(20, 10, 20, 20)
        self.main_layout.setSpacing(20)
        
        # Left side container (takes 70% width)
        self.left_container = QtWidgets.QWidget(self.central_widget)
        self.left_container.setObjectName("left_container")
        self.left_layout = QtWidgets.QVBoxLayout(self.left_container)
        self.left_layout.setContentsMargins(0, 0, 0, 0)
        self.left_layout.setSpacing(20)
        
        # Top widget in left container (map view)
        self.widget_4 = QtWidgets.QWidget(self.left_container)
        self.widget_4.setStyleSheet("border-radius: 10px; background-color: #101419;")
        self.widget_4.setObjectName("widget_4")
        self.left_layout.addWidget(self.widget_4, stretch=6)  # 60% of left space
        
        # Bottom widget in left container (status info)
        self.widget_2 = QtWidgets.QWidget(self.left_container)
        self.widget_2.setStyleSheet("border-radius: 10px; background-color: #101419;")
        self.widget_2.setObjectName("widget_2")
        
        # Layout for the bottom widget
        self.bottom_layout = QtWidgets.QHBoxLayout(self.widget_2)
        self.bottom_layout.setContentsMargins(20, 20, 20, 20)
        self.bottom_layout.setSpacing(20)
        
        # Orientation widget
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setStyleSheet("background-color: #1D1D1D; border: 1px solid #B9B9B9;")
        self.widget_5.setObjectName("widget_5")
        self.orientation_layout = QtWidgets.QVBoxLayout(self.widget_5)
        self.orientation_layout.setContentsMargins(20, 10, 20, 10)
        
        self.label_2 = QtWidgets.QLabel(self.widget_5)
        self.label_2.setStyleSheet("border: 0px; font-weight: bold; color: #A4A4A5; font-size: 20px; background-color: transparent;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.orientation_layout.addWidget(self.label_2)
        
        self.label_7 = QtWidgets.QLabel(self.widget_5)
        self.label_7.setStyleSheet("border: 0px; font-weight: 600; color: white; font-size: 28px; background-color: transparent;")
        self.label_7.setObjectName("label_7")
        self.orientation_layout.addWidget(self.label_7)
        
        self.label_8 = QtWidgets.QLabel(self.widget_5)
        self.label_8.setStyleSheet("border: 0px; font-weight: 600; color: white; font-size: 28px; background-color: transparent;")
        self.label_8.setObjectName("label_8")
        self.orientation_layout.addWidget(self.label_8)
        
        self.label_9 = QtWidgets.QLabel(self.widget_5)
        self.label_9.setStyleSheet("border: 0px; font-weight: 600; color: white; font-size: 28px; background-color: transparent;")
        self.label_9.setObjectName("label_9")
        self.orientation_layout.addWidget(self.label_9)
        
        self.bottom_layout.addWidget(self.widget_5, stretch=2)  # 20% of bottom space
        
        # Center widget with logo and safety info
        self.center_widget = QtWidgets.QWidget(self.widget_2)
        self.center_widget.setObjectName("center_widget")
        self.center_layout = QtWidgets.QVBoxLayout(self.center_widget)
        self.center_layout.setContentsMargins(0, 0, 0, 0)
        
        # Logo
        self.label_23 = QtWidgets.QLabel(self.center_widget)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setPixmap(QtGui.QPixmap("assets/images/logo.png"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.center_layout.addWidget(self.label_23)
        
        # Safety widget
        self.widget_6 = QtWidgets.QWidget(self.center_widget)
        self.widget_6.setStyleSheet("background-color: #1D1D1D; border: 1px solid #B9B9B9;")
        self.widget_6.setObjectName("widget_6")
        self.safety_layout = QtWidgets.QVBoxLayout(self.widget_6)
        self.safety_layout.setContentsMargins(20, 10, 20, 10)
        
        self.label_3 = QtWidgets.QLabel(self.widget_6)
        self.label_3.setStyleSheet("border: 0px; font-weight: bold; color: #A4A4A5; font-size: 18px; background-color: transparent;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.safety_layout.addWidget(self.label_3)
        
        self.label_4 = QtWidgets.QLabel(self.widget_6)
        self.label_4.setStyleSheet("border: 0px; font-weight: 550; color: white; font-size: 23px; background-color: transparent;")
        self.label_4.setObjectName("label_4")
        self.safety_layout.addWidget(self.label_4)
        
        self.label_5 = QtWidgets.QLabel(self.widget_6)
        self.label_5.setStyleSheet("border: 0px; font-weight: 550; color: white; font-size: 23px; background-color: transparent;")
        self.label_5.setObjectName("label_5")
        self.safety_layout.addWidget(self.label_5)
        
        self.widget_12 = QtWidgets.QWidget(self.widget_6)
        self.widget_12.setStyleSheet("border-radius: 5px; border: none; background-color: #A4A4A5;")
        self.widget_12.setFixedSize(21, 21)
        self.safety_layout.addWidget(self.widget_12, alignment=QtCore.Qt.AlignLeft)
        
        self.widget_13 = QtWidgets.QWidget(self.widget_6)
        self.widget_13.setStyleSheet("border-radius: 5px; border: none; background-color: #A4A4A5;")
        self.widget_13.setFixedSize(21, 21)
        self.safety_layout.addWidget(self.widget_13, alignment=QtCore.Qt.AlignLeft)
        
        self.center_layout.addWidget(self.widget_6)
        self.bottom_layout.addWidget(self.center_widget, stretch=3)  # 30% of bottom space
        
        # Velocity widget
        self.widget_7 = QtWidgets.QWidget(self.widget_2)
        self.widget_7.setStyleSheet("background-color: #1D1D1D; border: 1px solid #B9B9B9;")
        self.widget_7.setObjectName("widget_7")
        self.velocity_layout = QtWidgets.QVBoxLayout(self.widget_7)
        self.velocity_layout.setContentsMargins(20, 10, 20, 10)
        
        self.label_6 = QtWidgets.QLabel(self.widget_7)
        self.label_6.setStyleSheet("border: 0px; font-weight: bold; color: #A4A4A5; font-size: 20px; background-color: transparent;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.velocity_layout.addWidget(self.label_6)
        
        self.label_10 = QtWidgets.QLabel(self.widget_7)
        self.label_10.setStyleSheet("border: 0px; font-weight: 600; color: white; font-size: 28px; background-color: transparent;")
        self.label_10.setObjectName("label_10")
        self.velocity_layout.addWidget(self.label_10)
        
        self.label_11 = QtWidgets.QLabel(self.widget_7)
        self.label_11.setStyleSheet("border: 0px; font-weight: 600; color: white; font-size: 28px; background-color: transparent;")
        self.label_11.setObjectName("label_11")
        self.velocity_layout.addWidget(self.label_11)
        
        self.label_12 = QtWidgets.QLabel(self.widget_7)
        self.label_12.setStyleSheet("border: 0px; font-weight: 600; color: white; font-size: 28px; background-color: transparent;")
        self.label_12.setObjectName("label_12")
        self.velocity_layout.addWidget(self.label_12)
        
        self.bottom_layout.addWidget(self.widget_7, stretch=2)  # 20% of bottom space
        self.left_layout.addWidget(self.widget_2, stretch=4)  # 40% of left space
        
        # Right side container (takes 30% width)
        self.right_container = QtWidgets.QWidget(self.central_widget)
        self.right_container.setObjectName("right_container")
        self.right_layout = QtWidgets.QVBoxLayout(self.right_container)
        self.right_layout.setContentsMargins(0, 0, 0, 0)
        self.right_layout.setSpacing(20)
        
        # Drone image
        self.label = QtWidgets.QLabel(self.right_container)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setPixmap(QtGui.QPixmap("assets/images/drone.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.right_layout.addWidget(self.label, stretch=2)  # 20% of right space
        
        # Altitude and Battery widgets
        self.top_right_widget = QtWidgets.QWidget(self.right_container)
        self.top_right_widget.setObjectName("top_right_widget")
        self.top_right_layout = QtWidgets.QHBoxLayout(self.top_right_widget)
        self.top_right_layout.setContentsMargins(0, 0, 0, 0)
        self.top_right_layout.setSpacing(20)
        
        # Altitude widget
        self.widget_10 = QtWidgets.QWidget(self.top_right_widget)
        self.widget_10.setStyleSheet("background-color: #1D1D1D; border: 1px solid #B9B9B9;")
        self.widget_10.setObjectName("widget_10")
        self.altitude_layout = QtWidgets.QVBoxLayout(self.widget_10)
        self.altitude_layout.setContentsMargins(10, 10, 10, 10)
        
        self.label_20 = QtWidgets.QLabel(self.widget_10)
        self.label_20.setStyleSheet("border: 0px; font-weight: bold; color: #A4A4A5; font-size: 18px; background-color: transparent;")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.altitude_layout.addWidget(self.label_20)
        
        self.label_19 = QtWidgets.QLabel(self.widget_10)
        self.label_19.setStyleSheet("border: 0px; font-weight: 600; color: white; font-size: 40px; background-color: transparent;")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.altitude_layout.addWidget(self.label_19)
        
        self.top_right_layout.addWidget(self.widget_10, stretch=1)
        
        # Battery widget
        self.widget_11 = QtWidgets.QWidget(self.top_right_widget)
        self.widget_11.setStyleSheet("background-color: #1D1D1D; border: 1px solid #B9B9B9;")
        self.widget_11.setObjectName("widget_11")
        self.battery_layout = QtWidgets.QVBoxLayout(self.widget_11)
        self.battery_layout.setContentsMargins(10, 10, 10, 10)
        
        self.label_22 = QtWidgets.QLabel(self.widget_11)
        self.label_22.setStyleSheet("border: 0px; font-weight: bold; color: #A4A4A5; font-size: 18px; background-color: transparent;")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.battery_layout.addWidget(self.label_22)
        
        self.label_21 = QtWidgets.QLabel(self.widget_11)
        self.label_21.setStyleSheet("border: 0px; font-weight: 600; color: white; font-size: 36px; background-color: transparent;")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.battery_layout.addWidget(self.label_21)
        
        self.top_right_layout.addWidget(self.widget_11, stretch=1)
        self.right_layout.addWidget(self.top_right_widget, stretch=1)  # 10% of right space
        
        # Control modes widget
        self.widget_9 = QtWidgets.QWidget(self.right_container)
        self.widget_9.setStyleSheet("background-color: #1D1D1D; border: 1px solid #B9B9B9;")
        self.widget_9.setObjectName("widget_9")
        self.control_layout = QtWidgets.QVBoxLayout(self.widget_9)
        self.control_layout.setContentsMargins(20, 10, 20, 10)
        
        self.label_17 = QtWidgets.QLabel(self.widget_9)
        self.label_17.setStyleSheet("border: 0px; font-weight: bold; color: #A4A4A5; font-size: 19px; background-color: transparent;")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.control_layout.addWidget(self.label_17)
        
        self.label_18 = QtWidgets.QLabel(self.widget_9)
        self.label_18.setStyleSheet("border: 0px; font-weight: 550; color: white; font-size: 20px; background-color: transparent;")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.control_layout.addWidget(self.label_18)
        
        self.toolButton = QtWidgets.QToolButton(self.widget_9)
        self.toolButton.setStyleSheet("background-color: white;")
        self.toolButton.setFixedSize(30, 26)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/images/power.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setObjectName("toolButton")
        self.control_layout.addWidget(self.toolButton, alignment=QtCore.Qt.AlignCenter)
        
        self.right_layout.addWidget(self.widget_9, stretch=1)  # 10% of right space
        
        # Safe coordinates widget
        self.widget_8 = QtWidgets.QWidget(self.right_container)
        self.widget_8.setStyleSheet("background-color: #1D1D1D; border: 1px solid #B9B9B9;")
        self.widget_8.setObjectName("widget_8")
        self.coordinates_layout = QtWidgets.QVBoxLayout(self.widget_8)
        self.coordinates_layout.setContentsMargins(20, 10, 20, 10)
        
        self.label_14 = QtWidgets.QLabel(self.widget_8)
        self.label_14.setStyleSheet("border: 0px; font-weight: bold; color: #A4A4A5; font-size: 20px; background-color: transparent;")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.coordinates_layout.addWidget(self.label_14)
        
        self.label_13 = QtWidgets.QLabel(self.widget_8)
        self.label_13.setStyleSheet("border: 0px; font-weight: 550; color: white; font-size: 25px; background-color: transparent;")
        self.label_13.setObjectName("label_13")
        self.coordinates_layout.addWidget(self.label_13)
        
        self.label_15 = QtWidgets.QLabel(self.widget_8)
        self.label_15.setStyleSheet("border: 0px; font-weight: 550; color: white; font-size: 25px; background-color: transparent;")
        self.label_15.setObjectName("label_15")
        self.coordinates_layout.addWidget(self.label_15)
        
        self.label_16 = QtWidgets.QLabel(self.widget_8)
        self.label_16.setStyleSheet("border: 0px; font-weight: 550; color: white; font-size: 25px; background-color: transparent;")
        self.label_16.setObjectName("label_16")
        self.coordinates_layout.addWidget(self.label_16)
        
        self.right_layout.addWidget(self.widget_8, stretch=6)  # 60% of right space
        
        # Add left and right containers to main layout
        self.main_layout.addWidget(self.left_container, stretch=7)  # 70% width
        self.main_layout.addWidget(self.right_container, stretch=3)  # 30% width
        
        MainWindow.setCentralWidget(self.central_widget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Orientation"))
        self.label_7.setText(_translate("MainWindow", "X : 20.25"))
        self.label_8.setText(_translate("MainWindow", "Y : 20.25"))
        self.label_9.setText(_translate("MainWindow", "Z : 20.25"))
        self.label_3.setText(_translate("MainWindow", "Safety"))
        self.label_4.setText(_translate("MainWindow", "Battery  Low "))
        self.label_5.setText(_translate("MainWindow", "Lost  Link"))
        self.label_6.setText(_translate("MainWindow", "Velocity"))
        self.label_10.setText(_translate("MainWindow", "X : 20.25"))
        self.label_11.setText(_translate("MainWindow", "Y : 20.25"))
        self.label_12.setText(_translate("MainWindow", "Z : 20.25"))
        self.label_13.setText(_translate("MainWindow", "1 : X:20.56  Y : 25.36 "))
        self.label_14.setText(_translate("MainWindow", "Safe Co-ordinates"))
        self.label_15.setText(_translate("MainWindow", "2 : X:20.56  Y : 25.36 "))
        self.label_16.setText(_translate("MainWindow", "3 : X:20.56  Y : 25.36 "))
        self.label_17.setText(_translate("MainWindow", "Control Modes"))
        self.label_18.setText(_translate("MainWindow", "Autonomous"))
        self.label_19.setText(_translate("MainWindow", "20.5"))
        self.label_20.setText(_translate("MainWindow", "Altitude"))
        self.label_21.setText(_translate("MainWindow", "80%"))
        self.label_22.setText(_translate("MainWindow", "Battery"))